version: "3.9"

services:
  php-test:
    image: calc-php
    container_name: calc-php-test
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./api:/var/www/html

  database-test:
    image: mysql
    container_name: calc-db-test
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-Admin123!}
      MYSQL_PASSWORD: ${DB_PASSWORD:-calc0123!!}
      MYSQL_USER: ${DB_USER:-calc}
      MYSQL_DATABASE: ${DB_DATABASE:-calc_db_test}
