version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: calc-nginx
    ports:
      - "8888:8888"
    volumes:
      - ./api/public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    image: calc-php
    container_name: calc-php
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./api:/var/www/html

  react:
    image: calc-client
    container_name: calc-client
    ports:
      - "8080:8080"
    build:
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./client:/app/client
    stdin_open: true
    tty: true

  database:
    image: mysql
    container_name: calc-db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-Admin123!}
      MYSQL_PASSWORD: ${DB_PASSWORD:-calc0123!!}
      MYSQL_USER: ${DB_USER:-calc}
      MYSQL_DATABASE: ${DB_DATABASE:-calc_db}

volumes:
  db:
